# app.yaml
runtime: python312
entrypoint: uvicorn main:app --host 0.0.0.0 --port 8080

env_variables:
  # Google Cloud Configuration
  VERTEX_AI_PROJECT_ID: "hackathon-472205"
  VERTEX_AI_LOCATION: "us-central1"
  GCS_BUCKET_NAME: "hackathon-asset-genai"

  # Image Generation Settings
  GEMINI_API_KEY: "AIzaSyCsQPSpRdM6oSNTawP5VgJ5qZjYbxgPzZU"
  IMAGEN_SEED: "42"

  # Auth & Security
  JWT_SECRET_KEY: "mynameisrohitkumar46"
  GOOGLE_CLIENT_ID: "674848395794-jsfevf8iifvmjh33go3cuqf96p2liete.apps.googleusercontent.com"

  # Database Connection
  DATABASE_URL: "postgresql://postgres.adnrxgcytqchbsnnxcms:RamKrishna%400192@aws-1-us-east-2.pooler.supabase.com:6543/postgres"

  # --- IMPORTANT: UPDATE THIS AFTER DEPLOYING YOUR FRONTEND ---
  CORS_ORIGINS: "https://your-frontend-url.web.app,http://localhost:5173"